// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_episodes_showId_season_ from "./routes/api/episodes/[showId]/[season].ts";
import * as $api_seasons_id_ from "./routes/api/seasons/[id].ts";
import * as $api_stream_id_ from "./routes/api/stream/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $watch_id_ from "./routes/watch/[id].tsx";
import * as $PersonSearch from "./islands/PersonSearch.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/episodes/[showId]/[season].ts": $api_episodes_showId_season_,
    "./routes/api/seasons/[id].ts": $api_seasons_id_,
    "./routes/api/stream/[id].ts": $api_stream_id_,
    "./routes/index.tsx": $index,
    "./routes/watch/[id].tsx": $watch_id_,
  },
  islands: {
    "./islands/PersonSearch.tsx": $PersonSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
